### ISSUE TITLE
broken thing

### ISSUE THREAD

**Issue by GodyFromDiscord** [ascella-dev/issue-tracker#1]
this command is very broken xdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd

**Comment by KierenPH** [comment]
ah yes big issue will fix

**Comment by GodyFromDiscord** [comment]
bug fixed

**Comment by GodyFromDiscord** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue](https://trello.com/c/CL7EoEFC/223-issue)
