### ISSUE TITLE
Music bot disconnects after two minutes(?) even with music playing.

### ISSUE THREAD

**Issue by xplrkai** [ascella-dev/issue-tracker#2]
**Issue/Bug:** Bot disconnects after 2 mins 
**Explain what happened:** When music is playing, the bot will disconnect as normal as if nothing is playing and shows the disconnected embed.
**Anything Else?:** Here's a screenshot: https://i.imgur.com/EpEjf7L.png < _It plays the song then it would randomly disonnect?_

**Comment by GodyFromDiscord** [comment]
Known issue is already in progress of being fixed
